In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
dat = pd.read_csv("F.txt", sep="\t", header=None)
dat

0  1   2  3
0     0  0   0  0
1     0  0   0  0
2     0  0   0  0
3     0  0   0  0
4     0  0   0  0
...  .. ..  .. ..
3819  0  0  49  0
3820  0  0  51  0
3821  0  0  51  0
3822  0  0  54  0
3823  0  0  54  0

[3824 rows x 4 columns]

In [3]:
X = list(dat[3]) # 4th voice
print(X[:10])

[0, 0, 0, 0, 0, 0, 0, 0, 42, 42]


In [4]:
set_X = list(set(X))
print(len(set_X))
# Conversion to n dimensional binary vector
X_vec = []
for x in X:
    n = set_X.index(x)
    vec = [1 if i==n else 0 for i in range(len(set_X))]
    X_vec.append(vec)
X_vec[0]

26


[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [5]:
# Sliding window with one-step forecasting
X_t0 = np.array(X_vec[:-1])
y = np.array(X_vec[1:])
print(X_t0[0])
print(y[0])

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [6]:
reg = LinearRegression().fit(X_t0, y)

In [7]:
reg.predict([X_t0[-1]])

array([[ 9.59716797e-01, -7.28583860e-17, -1.21430643e-16,
        -2.12503626e-17, -2.08166817e-16, -6.93889390e-18,
         3.26442719e-03, -6.33174069e-17,  3.29589844e-03,
         3.26633453e-03, -7.97972799e-17,  5.29479980e-03,
         1.69372559e-03,  7.08007812e-03,  1.84631348e-03,
         3.57055664e-03,  4.89997864e-03,  4.74880552e-17,
         1.65557861e-03,  1.59931183e-03,  2.88391113e-03,
        -1.04904175e-05, -1.14440918e-05, -3.27971157e-18,
        -5.01443505e-18, -5.09913834e-18]])